services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging-telegram
    ports:
      - "3000:3000"
    environment:
      BROKER_URL: redis://redis:6379/0
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  redis-data: